### ISSUE TITLE
Bitcode support error

### ISSUE THREAD

**Issue by paulocoutinhox** [lasote/conan-darwin-toolchain#6]
Hi,

I don't know why, but all my libs are compiled without bitcode, but is True by default.

When i force to true, i change my profile:

```
include(default)

[settings]
os=iOS
os.version=9.0
arch=armv7
bitcode=True

[build_requires]
darwin-toolchain/1.0.4@theodelrieu/stable
```

But get error:

```
conan install .. --profile ios_profile -s arch=armv7
ERROR: 'settings.bitcode' doesn't exist
'settings' possible configurations are ['arch', 'arch_build', 'arch_target', 'build_type', 'compiler', 'cppstd', 'os', 'os_build', 'os_target']
make: *** [build-ios] Error 1
```

Can you help me?

**Comment by theodelrieu** [comment]
Hello,

About the latter, `bitcode` is an option, not a setting.

But the former is very weird, could you paste the compiler command-line?

**Comment by paulocoutinhox** [comment]
Hi,

Im new to conan, what this mean "bitcode is an option, not a setting."?

And how i can change this "option"?

Thanks.

**Comment by theodelrieu** [comment]
The difference between options and settings is a bit hard to grasp at first, but basically settings are project-wide (e.g. the OS you're targeting, the build type, etc), whereas options are package-dependent.

To solve the issue you can either:

* move `darwin-toolchain:bitcode=True` under an `[options]` section in your profile
* add `-o darwin-toolchain:bitcode=True` to the `conan install` command line

But this still does not explain why you do not get bitcode libraries by default...
Could you run `lipo libmylib.a -info` and paste the result?

**Comment by paulocoutinhox** [comment]
Hi,

```
$ lipo dist/ios/Core.framework/Core -info
Architectures in the fat file: dist/ios/Core.framework/Core are: armv7 armv7s arm64 arm64e 
```

Thanks.

**Comment by theodelrieu** [comment]
Hmm, could you try to remove the explicit `bitcode` option and build again? I'd like to see the full compiler output.
